apiVersion: v1
kind: ConfigMap
metadata:
  name: eventhub-config
data:
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "eventhudb"
  DB_USER: "eventhub_user"
