apiVersion: v1
kind: Secret
metadata:
  name: eventhub-secret
type: Opaque
stringData:
  DB_PASSWORD: "eventhub_pass"
  DJANGO_SECRET_KEY: "django-insecure--f67ll=2-b2qolla9=1f8mtg@s=l8^y8aj=@ij-0f4)eg@%8(0"
